#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/fancontrol" ]; then
	update-rc.d fancontrol start 20 2 3 4 5 . >/dev/null
	if [ -n "$2" ]; then
		_dh_action=restart
	else
		_dh_action=start
	fi
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d fancontrol $_dh_action || exit $?
	else
		/etc/init.d/fancontrol $_dh_action || exit $?
	fi
fi
# End automatically added section
